// Auto-generated by Aurous Timetable Bot — do not edit manually
const SCHEDULE_DATA = {
  "batch": "12TH POLARIS R 2026-27",
  "week": "11 MAY - 17 MAY 2026",
  "schedule": {
    "MONDAY": [],
    "TUESDAY": [
      {
        "time": "04:00-05:20",
        "room": "C1 CR 202",
        "teacher": "PMP"
      },
      {
        "time": "05:30-06:55",
        "room": "C1 CR 202",
        "teacher": "CRB"
      },
      {
        "time": "07:05-08:30",
        "room": "C1 CR 202",
        "teacher": "MRP"
      }
    ],
    "WEDNESDAY": [
      {
        "time": "04:00-05:20",
        "room": "C1 CR 202",
        "teacher": "PMP"
      },
      {
        "time": "05:30-06:55",
        "room": "C1 CR 202",
        "teacher": "CRB"
      },
      {
        "time": "07:05-08:30",
        "room": "C1 CR 202",
        "teacher": "MRP"
      }
    ],
    "THURSDAY": [],
    "FRIDAY": [
      {
        "time": "04:00-05:20",
        "room": "C1 CR 202",
        "teacher": "PMP"
      },
      {
        "time": "05:30-06:55",
        "room": "C1 CR 202",
        "teacher": "CRB"
      },
      {
        "time": "07:05-08:30",
        "room": "C1 CR 202",
        "teacher": "MRP"
      }
    ],
    "SATURDAY": [
      {
        "time": "04:00-05:20",
        "room": "C1 CR 202",
        "teacher": "PMP"
      },
      {
        "time": "05:30-06:55",
        "room": "C1 CR 202",
        "teacher": "CRB"
      },
      {
        "time": "07:05-08:30",
        "room": "C1 CR 202",
        "teacher": "MRP"
      }
    ],
    "SUNDAY": []
  },
  "tests": [
    {
      "name": "MINOR TEST # 2 JEE ADV",
      "date": "17TH MAY 2026",
      "type": "JEE Advanced",
      "week": "11 MAY - 17 MAY 2026"
    },
    {
      "name": "MINOR TEST # 1",
      "date": "17TH MAY 2026",
      "type": "Test / Exam",
      "week": "11 MAY - 17 MAY 2026"
    },
    {
      "name": "2 JEE ADV ACTIVITY : INTERNAL TEST # 1",
      "date": "24TH MAY 2026",
      "type": "JEE Advanced",
      "week": "11 MAY - 17 MAY 2026"
    }
  ],
  "generated_at": "11 May 2026, 05:57"
};
